Don't swallow exceptions
This prevents legitimate exceptions from being swallowed while the
plugin is recording test results.

We ran into an issue where our unit test results silently failed to be
recorded because our slave node clocks were out of sync with master.
Because this AbortException was being swallowed, the job output contained
no useful information to troubleshoot the issue.

Here is the tail end of the job output when master and slave node clocks
are out of sync before and after this patch.

Before:
Recording NUnit tests results
Finished: FAILURE

After:
Recording NUnit tests results
ERROR: Publisher hudson.plugins.nunit.NUnitPublisher aborted due to exception
hudson.AbortException: Clock on this slave is out of sync with the master, and therefore
I can't figure out what test results are new and what are old.
Please keep the slave clock in sync with the master.
    at hudson.tasks.junit.TestResult.parse(TestResult.java:173)
    at hudson.tasks.junit.TestResult.parse(TestResult.java:140)
    at hudson.tasks.junit.TestResult.<init>(TestResult.java:116)
    at hudson.plugins.nunit.NUnitPublisher$1.invoke(NUnitPublisher.java:239)
    at hudson.plugins.nunit.NUnitPublisher$1.invoke(NUnitPublisher.java:222)
    at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2309)
    at hudson.remoting.UserRequest.perform(UserRequest.java:118)
    at hudson.remoting.UserRequest.perform(UserRequest.java:48)
    at hudson.remoting.Request$2.run(Request.java:326)
    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at hudson.remoting.Engine$1$1.run(Engine.java:58)
    at java.lang.Thread.run(Unknown Source)
Finished: FAILURE